## Spam Project 

In [1]:
corpus = [
    "hello python is awesome",
    "python is modern language",
    "hello how are you",
    "i am awesome",
    "this is best time",
]

#### BoW
    a model which can extract information out of corpus

1. Building Vocabulary

In [2]:
corpus = [
    "hello python is awesome",
    "python is modern language",
    "hello how are you",
    "i am awesome",
    "this is best time",
]

    word to vector  -> d =  { 'am': 0, 'are': 1, 'awesome': 2 }
    # i = d.get('awesome') # 2

    vector to word -> d = { 0: 'am', 1: 'are', 2: 'awesome' }
    # word = d.get(1) # are
   

In [4]:
def build_vocab(corpus):
    vocab = []
    for document in corpus:
        for word in document.split():
            word = word.strip().lower()
            if word not in vocab:
                vocab.append(word)
    vocab.sort()
    w2v = { word:vector for vector,word in enumerate(vocab)}
    v2w = { vector:word for vector, word in enumerate(vocab)}
    return w2v, v2w
            

In [5]:
w2v, v2w = build_vocab(corpus)


In [6]:
print(w2v)

{'am': 0, 'are': 1, 'awesome': 2, 'best': 3, 'hello': 4, 'how': 5, 'i': 6, 'is': 7, 'language': 8, 'modern': 9, 'python': 10, 'this': 11, 'time': 12, 'you': 13}


In [7]:
w2v['this']

11

In [8]:
v2w[11]

'this'

In [9]:
len(w2v)

14

In [10]:
corpus
# m = 5, n = 14

['hello python is awesome',
 'python is modern language',
 'hello how are you',
 'i am awesome',
 'this is best time']

In [11]:
from sklearn.base import BaseEstimator, TransformerMixin

In [12]:
class Vectorizer(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.vocab_ = {}
        self.vocab_size_ = None
    def fit(self, corpus):
        vocab = []
        for document in corpus:
            for word in document.split():
                if word not in vocab:
                    vocab.append(word)
        vocab.sort()
        self.vocab_size_ = len(vocab)
        self.vocab_ = { w:v for v, w in enumerate(vocab) }
    def transform(self, corpus):
        vectors = []
        for document in corpus:
            vector = [ 0 ] * self.vocab_size_
            # [ 0, 0, 0, 0, 0, 0, 0, 0 ]
            for word in document.split():
                word = word.strip().lower()
                if word in self.vocab_:
                    i = self.vocab_[word]
                    vector[i] += 1
            vectors.append(vector)
        return vectors

In [13]:
corpus = [
    "hello python is awesome awesome awesome",
    "python is modern language",
    "hello how are you",
    "i am awesome",
    "this is best time",
]

In [14]:
vector = Vectorizer()

In [15]:
vector.fit(corpus)

In [16]:
vector.vocab_
#['am', 'are', 'awesome', 'best', 'hello', 'how', 'i', 'is', 'language', 'modern', 'python', 'this', 'time', 'you']

{'am': 0,
 'are': 1,
 'awesome': 2,
 'best': 3,
 'hello': 4,
 'how': 5,
 'i': 6,
 'is': 7,
 'language': 8,
 'modern': 9,
 'python': 10,
 'this': 11,
 'time': 12,
 'you': 13}

In [17]:
vc = vector.transform(corpus)

In [18]:
print(*corpus, sep='\n')

hello python is awesome awesome awesome
python is modern language
hello how are you
i am awesome
this is best time


In [19]:
#['am', 'are', 'awesome', 'best', 'hello', 'how', 'i', 'is', 'language',
#   0     1        2         3       4       5     6     7       8  
# 'modern', 'python', 'this', 'time', 'you']
#    9         10        11      12     13
#print(*range(14), sep=', ')
print(*vc, sep='\n')
# sparse matrix # 50000, 100 -> 1, 4900 -> 0

[0, 0, 3, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0]
[0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1]
[1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0]


In [20]:
from pprint import pprint

In [21]:
corpus = [
    "hello world", 
    "hi world", 
    "bye world", 
    "good bye world"
]

word_model = Vectorizer()
word_model.fit(corpus) # vocab
vcs = word_model.transform(corpus)
print(*vcs, sep='\n')
new_messege = [ 'hello hello hi hi', 'hello hi bye', 'hi sachin how are you']
vcs = word_model.transform(new_messege)
print(*new_messege, sep='\n')
print(*vcs, sep='\n') # m x n 

[0, 0, 1, 0, 1]
[0, 0, 0, 1, 1]
[1, 0, 0, 0, 1]
[1, 1, 0, 0, 1]
hello hello hi hi
hello hi bye
hi sachin how are you
[0, 0, 2, 2, 0]
[1, 0, 1, 1, 0]
[0, 0, 0, 1, 0]


In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
model = CountVectorizer()
model.fit(corpus)
tr = model.transform(corpus).toarray()
tr
vcs = model.transform(new_messege).toarray()
print(*new_messege, sep='\n')
print(*vcs, sep='\n') # m x n 

hello hello hi hi
hello hi bye
hi sachin how are you
[0 0 2 2 0]
[1 0 1 1 0]
[0 0 0 1 0]


In [24]:
#            0     1        2       3      4
# vocab =['bye', 'good', 'hello', 'hi', 'world']

In [25]:
vectors = [
    [ 0, 0, 1, 0, 1], # "hello world"
    [ 0, 0, 0, 1, 1], # "hi world"
    [ 1, 0, 0, 0, 1], # "bye world"
    [ 1, 1, 0, 0, 1], # "good bye world"
]
# 4 * 5

###### Text data into a numerical vector 

In [26]:
!ls

2.TextProcessing.ipynb
Project
SpamHamProject.ipynb
spam.csv


In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [28]:
df = pd.read_csv('spam.csv', encoding='latin')

In [29]:
df.isna().sum() / len(df)*100

v1             0.000000
v2             0.000000
Unnamed: 2    99.102656
Unnamed: 3    99.784637
Unnamed: 4    99.892319
dtype: float64

In [30]:
df.columns

Index(['v1', 'v2', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], dtype='object')

In [31]:
df.drop(['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'], axis=1, inplace=True)

In [32]:
df.rename({'v1': 'label', 'v2': 'message'}, axis=1, inplace=True)

In [33]:
df['message'] = df.message.str.lower()

In [34]:
df.head()

label                                            message
0   ham  go until jurong point, crazy.. available only ...
1   ham                      ok lar... joking wif u oni...
2  spam  free entry in 2 a wkly comp to win fa cup fina...
3   ham  u dun say so early hor... u c already then say...
4   ham  nah i don't think he goes to usf, he lives aro...

In [ ]:
airnb, medium, quor

### before converting text data into vector you need to preprocess it

    1. Remove Stop Words
    2. Remove Punctuations
    3. Apply Stemming / Lemmatization
    4. Vectorizaion
    5. TF/IDF Vector
   

In [35]:
y = df['label']

In [36]:
y.value_counts() / len(y) # imbalance

ham     0.865937
spam    0.134063
Name: label, dtype: float64

In [37]:
X = df['message']

In [38]:
vectorizer = CountVectorizer()

In [39]:
vectorizer.fit(X)

CountVectorizer()

In [40]:
X_tr = vectorizer.fit_transform(X)

In [41]:
X_tr

<5572x8672 sparse matrix of type '<class 'numpy.int64'>'
	with 73916 stored elements in Compressed Sparse Row format>

In [42]:
from sklearn.naive_bayes import MultinomialNB

In [43]:
model = MultinomialNB()

In [44]:
model.fit(X_tr, y)

MultinomialNB()

In [45]:
y_hat = model.predict(X_tr)

In [46]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y, y_hat))
print(classification_report(y, y_hat))
print(accuracy_score(y, y_hat))

[[4812   13]
 [  23  724]]
              precision    recall  f1-score   support

         ham       1.00      1.00      1.00      4825
        spam       0.98      0.97      0.98       747

    accuracy                           0.99      5572
   macro avg       0.99      0.98      0.99      5572
weighted avg       0.99      0.99      0.99      5572

0.9935391241923905


In [47]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
def evaluate(y, y_hat):
    print("Confusion Matrix")
    print(confusion_matrix(y, y_hat))
    print("\nClassification Report")
    print(classification_report(y, y_hat))
    print("\nAccuracy Score")
    print(accuracy_score(y, y_hat))

In [48]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, 
                                                   random_state=42)

In [50]:
model = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('naive bays model', MultinomialNB())
])

In [51]:
model.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()),
                ('naive bays model', MultinomialNB())])

In [52]:
y_hat = model.predict(X_train)
evaluate(y_train, y_hat)

Confusion Matrix
[[3851    9]
 [  16  581]]

Classification Report
              precision    recall  f1-score   support

         ham       1.00      1.00      1.00      3860
        spam       0.98      0.97      0.98       597

    accuracy                           0.99      4457
   macro avg       0.99      0.99      0.99      4457
weighted avg       0.99      0.99      0.99      4457


Accuracy Score
0.9943908458604442


In [53]:
y_hat = model.predict(X_test)
evaluate(y_test, y_hat)

Confusion Matrix
[[963   2]
 [ 16 134]]

Classification Report
              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       965
        spam       0.99      0.89      0.94       150

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115


Accuracy Score
0.9838565022421525


In [54]:
new_messege= [
    'free free free aboslute free everying click',
    'hello can you meet me tomorrow'
]

In [55]:
model.predict(new_messege)

array(['spam', 'ham'], dtype='<U4')