In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
# to scale numerical values
from sklearn.impute import SimpleImputer
# to impute missing values in Data
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
# to convert categorical features into numberical feature

from sklearn.pipeline import Pipeline
# to build a data preprocessing pipeline
import os
data_root_dir = "C:\\Users\\sachin\\OneDrive - Grras Solution Pvt. Ltd\\ML_BATCH_2021\\MachineLearning\\Notebooks\\datasets"
data_path = os.path.join(data_root_dir, 'housing\housing.csv')
housing = pd.read_csv(data_path)
X = housing.drop(['median_house_value'], axis=1).copy()
y = housing['median_house_value']


# to randomly split data into train and test part
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

num_features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']
cat_features = [ 'ocean_proximity' ]


In [2]:
from sklearn.preprocessing import StandardScaler
# to scale numerical values
from sklearn.impute import SimpleImputer
# to impute missing values in Data
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
# to convert categorical features into numberical feature

from sklearn.pipeline import Pipeline
# to build a data preprocessing pipeline

In [3]:
X_train.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
9950    -122.33     38.38                28.0       1020.0           169.0   
3547    -118.60     34.26                18.0       6154.0          1070.0   
4448    -118.21     34.07                47.0       1346.0           383.0   
6984    -118.02     33.96                36.0       2071.0           398.0   
4432    -118.20     34.08                49.0       1320.0           309.0   

      population  households  median_income ocean_proximity  
9950       504.0       164.0         4.5694          INLAND  
3547      3010.0      1034.0         5.6392       <1H OCEAN  
4448      1452.0       371.0         1.7292       <1H OCEAN  
6984       988.0       404.0         4.6226       <1H OCEAN  
4432      1405.0       328.0         2.4375       <1H OCEAN

In [4]:
X_train.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [5]:
num_features = ['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income']
cat_features = [ 'ocean_proximity' ]

In [6]:
X_train_num = X_train[num_features]
# Missing Values, Scale
X_train_cat = X_train[cat_features]
# OneHotEncoding

In [7]:
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')), #T1
    ('standard scaler', StandardScaler()), #T2
])

In [8]:
tr = num_pipeline.fit_transform(X_train_num)
X_train_num_tr = pd.DataFrame(tr, columns=X_train_num.columns)
X_train_num_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0  -1.381195  1.289422           -0.045376    -0.737644       -0.872454   
1   0.483377 -0.640792           -0.840169     1.587216        1.246544   
2   0.678333 -0.729807            1.464730    -0.590019       -0.369162   
3   0.773311 -0.781342            0.590458    -0.261713       -0.333885   
4   0.683331 -0.725122            1.623688    -0.601793       -0.543198   

   population  households  median_income  
0   -0.822910   -0.873927       0.367714  
1    1.394248    1.371062       0.930745  
2    0.015823   -0.339775      -1.127069  
3   -0.394696   -0.254620       0.395713  
4   -0.025760   -0.450734      -0.754294

In [9]:
X_train_num_tr.isna().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
dtype: int64

In [10]:
num_pipeline.named_steps['imputer'].statistics_

array([-118.49  ,   34.25  ,   29.    , 2138.5   ,  438.    , 1170.    ,
        412.    ,    3.5294])

In [11]:
num_pipeline.named_steps['standard scaler'].mean_

array([-119.56697614,   35.62775739,   28.57091812, 2648.94319283,
        539.96814438, 1434.11573401,  502.67284399,    3.8707156 ])

In [12]:
num_pipeline.named_steps['standard scaler'].var_

array([4.00183395e+00, 4.55599661e+00, 1.58304200e+02, 4.87661272e+06,
       1.80795891e+05, 1.27752329e+06, 1.50179314e+05, 3.61028250e+00])

In [13]:
cat_pipeline = OneHotEncoder()

In [14]:
X_train_cat_tr = cat_pipeline.fit_transform(X_train_cat).toarray()
cols = cat_pipeline.categories_[0]
X_train_cat_tr = pd.DataFrame(X_train_cat_tr, columns=cols)
X_train_cat_tr.head()

<1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
0        0.0     1.0     0.0       0.0         0.0
1        1.0     0.0     0.0       0.0         0.0
2        1.0     0.0     0.0       0.0         0.0
3        1.0     0.0     0.0       0.0         0.0
4        1.0     0.0     0.0       0.0         0.0

In [15]:
a = np.random.random((4,3))
b = np.random.random((4, 2))

In [16]:
a

array([[0.17554093, 0.46598734, 0.05829584],
       [0.1645392 , 0.10472337, 0.14829738],
       [0.58908087, 0.13905724, 0.12584458],
       [0.82346626, 0.26839774, 0.1162159 ]])

In [17]:
b

array([[0.13922082, 0.15986068],
       [0.48760561, 0.54212023],
       [0.50974834, 0.56551719],
       [0.91649748, 0.12700371]])

In [18]:
c = np.c_[a, b]
c

array([[0.17554093, 0.46598734, 0.05829584, 0.13922082, 0.15986068],
       [0.1645392 , 0.10472337, 0.14829738, 0.48760561, 0.54212023],
       [0.58908087, 0.13905724, 0.12584458, 0.50974834, 0.56551719],
       [0.82346626, 0.26839774, 0.1162159 , 0.91649748, 0.12700371]])

In [19]:
# Combining Feature Together to make single 
X_train_tr = pd.concat([X_train_num_tr, X_train_cat_tr], axis=1)

In [20]:
X_train_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0  -1.381195  1.289422           -0.045376    -0.737644       -0.872454   
1   0.483377 -0.640792           -0.840169     1.587216        1.246544   
2   0.678333 -0.729807            1.464730    -0.590019       -0.369162   
3   0.773311 -0.781342            0.590458    -0.261713       -0.333885   
4   0.683331 -0.725122            1.623688    -0.601793       -0.543198   

   population  households  median_income  <1H OCEAN  INLAND  ISLAND  NEAR BAY  \
0   -0.822910   -0.873927       0.367714        0.0     1.0     0.0       0.0   
1    1.394248    1.371062       0.930745        1.0     0.0     0.0       0.0   
2    0.015823   -0.339775      -1.127069        1.0     0.0     0.0       0.0   
3   -0.394696   -0.254620       0.395713        1.0     0.0     0.0       0.0   
4   -0.025760   -0.450734      -0.754294        1.0     0.0     0.0       0.0   

   NEAR OCEAN  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0

In [21]:
from sklearn.linear_model import SGDRegressor

In [22]:
model = SGDRegressor()

In [23]:
model.fit(X_train_tr, y_train)

SGDRegressor()

In [24]:
X_test_num = X_test[num_features]
X_test_cat = X_test[cat_features]
X_test_num_tr = num_pipeline.transform(X_test_num) # Only Transform
X_test_cat_tr = cat_pipeline.transform(X_test_cat).toarray()
X_test_tr = np.c_[X_test_num_tr, X_test_cat_tr]


In [25]:
y_hat = model.predict(X_test_tr) # ? 

In [26]:
np.round(y_hat[:5], 2)

array([247560.15, 130905.92, 157363.67, 141903.41, 282869.96])

In [27]:
y_test[:5].to_numpy()

array([151600.,  99200., 134500., 231700., 462900.])

In [28]:
residuals = np.absolute(y_hat - y_test)
residuals[:5].to_numpy()

array([ 95960.14688996,  31705.92026927,  22863.66841818,  89796.58683513,
       180030.03902524])

In [29]:
from sklearn.metrics import r2_score

In [30]:
print("Test Accuracy: ", r2_score(y_test, y_hat))

Test Accuracy:  0.6445402565210057


In [31]:
y_hat_train = model.predict(X_train_tr)
print("Train Accuracy: ", r2_score(y_train, y_hat_train))

Train Accuracy:  0.6426488103239041


## Final Pipeline

In [31]:
%%writefile housing_project.py
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
# to scale numerical values
from sklearn.impute import SimpleImputer
# to impute missing values in Data
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
# to convert categorical features into numberical feature

from sklearn.pipeline import Pipeline
# to build a data preprocessing pipeline
from sklearn.compose import ColumnTransformer
import os


from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor


from sklearn.metrics import mean_squared_error, r2_score


def rmse(y, y_hat):
    return np.sqrt(mean_squared_error(y, y_hat))

def model_report(models, X_train, X_test, y_train, y_test):
    for name, model in models:
        model.fit(X_train, y_train)
        y_hat_train = model.predict(X_train)
        y_hat_test  = model.predict(X_test)
        print("_"*80)
        print(f"Report For {name}".center(80))
        print()
        print(f"Training RMSE Error: {rmse(y_train, y_hat_train):.2f}" )
        print(f"Test     RMSE Error: {rmse(y_test, y_hat_test):.2f}")
        print()
        print(f"Training Accuracy: {r2_score(y_train, y_hat_train):.2f}")
        print(f"Test     Accuracy: {r2_score(y_test, y_hat_test):.2f}")
        print('\n\n')
        
def load_data():
    data_root_dir = "C:\\Users\\sachin\\OneDrive - Grras Solution Pvt. Ltd\\ML_BATCH_2021\\MachineLearning\\Notebooks\\datasets"
    data_path = os.path.join(data_root_dir, 'housing\housing.csv')
    housing = pd.read_csv(data_path)
    X = housing.drop(['median_house_value'], axis=1).copy()
    y = housing['median_house_value']
    return X, y





if __name__ == '__main__':

    # to randomly split data into train and test part
    X, y = load_data()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

    num_features = [ 'longitude', 'latitude', 'housing_median_age', 'total_rooms',
           'total_bedrooms', 'population', 'households', 'median_income']

    cat_features = [ 'ocean_proximity' ]

    #drop_features = ['longitude', 'latitude']

    #pass_through =  [ 'median_income']

    num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='median')), #T1
        ('standard scaler', StandardScaler()), #T2
    ])


    final_pipeline = ColumnTransformer([
        # (name, Transformer, column_list)
        ("numerical pipeline", num_pipeline, num_features),
        ("categorical pipeline", OneHotEncoder(), cat_features),
        # ('remove features', 'drop', drop_features),
        # ('pass throgh', 'passthrough', pass_through )
    ])

    X_train_tr = final_pipeline.fit_transform(X_train)
    cat_col = list(final_pipeline.named_transformers_['categorical pipeline'].categories_[0])

    columns = num_features + list(cat_col) #+ pass_through

    X_train_tr = pd.DataFrame(X_train_tr, columns=columns)
    X_test_tr  =  final_pipeline.transform(X_test)
    X_test_tr = pd.DataFrame(X_test_tr, columns=columns)
    
    models = [
        ('Linear Regression', LinearRegression()),
        ('SGD Regressor', SGDRegressor(max_iter=10000)),
        ('Decision Tree', DecisionTreeRegressor(max_depth=7)),
        ('Support Vector Machines', SVR(kernel='linear')),
        ('Random Forest', RandomForestRegressor(max_depth=9)),
        ('K-Nearest Neighbors', KNeighborsRegressor(n_neighbors=51))
    ]

    model_report(models, X_train_tr, X_test_tr, y_train, y_test)

Overwriting housing_project.py


## Custom Transformers

In [32]:
!python housing_project.py

^C


### 15 - 20 minutes 

    Custom Transformers

### Feature Engineering

    columns drop
    
    column embededing 

    (longitude + latitude ) -> 48

In [36]:
X_train.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

In [35]:
X_train.corrwith(y_train).sort_values(ascending=False)

median_income         0.688904
total_rooms           0.132965
housing_median_age    0.099487
households            0.064043
total_bedrooms        0.048823
population           -0.024484
longitude            -0.038349
latitude             -0.150574
dtype: float64

In [38]:
long_lat = X_train['longitude'] + X_train['latitude']
print(np.corrcoef(long_lat, y_train)[0, 1])

-0.48973069783048284


In [39]:
hs_pop = X_train['households'] / X_train['population']
print(np.corrcoef(hs_pop, y_train)[0, 1])

0.2604202504653188


In [47]:
d = housing.dropna()
bd_room = d['total_bedrooms'] / d['total_rooms']
print(np.corrcoef(bd_room, d['median_house_value'])[0, 1])

-0.25588014941949794


    fit -> learn
    
    transform -> logic of transformation
    
    

In [50]:
X_train.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'ocean_proximity'],
      dtype='object')

Imputer -> Add_Features  -> Scaler

In [54]:
a = np.random.randint(10, 50, 20).reshape(4, 5)
a

array([[35, 38, 13, 49, 24],
       [30, 18, 37, 42, 16],
       [30, 44, 48, 49, 21],
       [45, 33, 43, 13, 32]])

In [58]:
a = np.c_[a, a[:, 1] + a[:, 4]]
a

array([[35, 38, 13, 49, 24, 62],
       [30, 18, 37, 42, 16, 34],
       [30, 44, 48, 49, 21, 65],
       [45, 33, 43, 13, 32, 65]])

In [61]:
# T1 -> T2 -> T3 -> 

from sklearn.base import BaseEstimator, TransformerMixin

class Add_Features(BaseEstimator, TransformerMixin):
    
    def __init__(self, add_rooms=True): 
        self.add_rooms = add_rooms # add_rooms -> is hyper parameter tunining
        self.ln  = 0 # longitude index
        self.lt  = 1 # latitude index
        self.pop = 5 # population index
        self.hs  = 6 # households
        self.rm  = 3 # total rooms
        self.bd  = 4 # total bedrooms
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        ln_lat = X[:, self.ln] + X[:, self.lt]
        hs_pop = X[:, self.hs] / X[:, self.pop]
        if self.add_rooms:
            bd_rm  = X[:, self.bd] / X[:, self.rm]
            return np.c_[X, ln_lat, hs_pop, bd_rm]
        
        return np.c_[X, ln_lat, hs_pop]
    
        
        
    

In [77]:
num_features = [ 'longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',]
cat_features = [ 'ocean_proximity' ]
num_pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),
    ('add features', Add_Features() ),
    ('scaler', StandardScaler() )
])

final_pipeline = ColumnTransformer([
    ('numerical pipeline', num_pipeline, num_features ),
    ('categorical pipeline', OneHotEncoder(), cat_features)
])

X_train_tr = final_pipeline.fit_transform(X_train)


cat_c = list(final_pipeline.named_transformers_['categorical pipeline'].categories_[0])
cols = num_features + ['long_lat', 'house_population', 'bedrooms_per_room'] + cat_c
X_train_tr = pd.DataFrame(X_train_tr, columns=cols)

In [78]:
X_train_tr.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0  -1.381195  1.289422           -0.045376    -0.737644       -0.872454   
1   0.483377 -0.640792           -0.840169     1.587216        1.246544   
2   0.678333 -0.729807            1.464730    -0.590019       -0.369162   
3   0.773311 -0.781342            0.590458    -0.261713       -0.333885   
4   0.683331 -0.725122            1.623688    -0.601793       -0.543198   

   population  households  median_income  long_lat  house_population  \
0   -0.822910   -0.873927       0.367714 -0.013262         -0.418878   
1    1.394248    1.371062       0.930745 -0.493012         -0.224283   
2    0.015823   -0.339775      -1.127069 -0.246986         -1.169214   
3   -0.394696   -0.254620       0.395713 -0.148576          0.477720   
4   -0.025760   -0.450734      -0.754294 -0.222384         -1.406035   

   bedrooms_per_room  <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN  
0          -0.726412        0.0     1.0     0.0       0.0         0.0  
1          -0.603529        1.0     0.0     0.0       0.0         0.0  
2           1.058197        1.0     0.0     0.0       0.0         0.0  
3          -0.328661        1.0     0.0     0.0       0.0         0.0  
4           0.300637        1.0     0.0     0.0       0.0         0.0

In [79]:
%%writefile housing_project.py
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler
# to scale numerical values
from sklearn.impute import SimpleImputer
# to impute missing values in Data
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
# to convert categorical features into numberical feature

from sklearn.pipeline import Pipeline
# to build a data preprocessing pipeline
from sklearn.compose import ColumnTransformer
import os


from sklearn.linear_model import LinearRegression, SGDRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor


from sklearn.metrics import mean_squared_error, r2_score

from sklearn.base import BaseEstimator, TransformerMixin

class Add_Features(BaseEstimator, TransformerMixin):
    def __init__(self, add_rooms=True): 
        self.add_rooms = add_rooms # add_rooms -> is hyper parameter tunining
        self.ln  = 0 # longitude index
        self.lt  = 1 # latitude index
        self.pop = 5 # population index
        self.hs  = 6 # households
        self.rm  = 3 # total rooms
        self.bd  = 4 # total bedrooms
        
    def fit(self, X, y=None):
        return self
    
    def transform(self, X, y=None):
        ln_lat = X[:, self.ln] + X[:, self.lt]
        hs_pop = X[:, self.hs] / X[:, self.pop]
        if self.add_rooms:
            bd_rm  = X[:, self.bd] / X[:, self.rm]
            return np.c_[X, ln_lat, hs_pop, bd_rm]
        
        return np.c_[X, ln_lat, hs_pop]

def rmse(y, y_hat):
    return np.sqrt(mean_squared_error(y, y_hat))

def model_report(models, X_train, X_test, y_train, y_test):
    for name, model in models:
        model.fit(X_train, y_train)
        y_hat_train = model.predict(X_train)
        y_hat_test  = model.predict(X_test)
        print("_"*80)
        print(f"Report For {name}".center(80))
        print()
        print(f"Training RMSE Error: {rmse(y_train, y_hat_train):.2f}" )
        print(f"Test     RMSE Error: {rmse(y_test, y_hat_test):.2f}")
        print()
        print(f"Training Accuracy: {r2_score(y_train, y_hat_train):.2f}")
        print(f"Test     Accuracy: {r2_score(y_test, y_hat_test):.2f}")
        print('\n\n')
        
def load_data():
    data_root_dir = "C:\\Users\\sachin\\OneDrive - Grras Solution Pvt. Ltd\\ML_BATCH_2021\\MachineLearning\\Notebooks\\datasets"
    data_path = os.path.join(data_root_dir, 'housing\housing.csv')
    housing = pd.read_csv(data_path)
    X = housing.drop(['median_house_value'], axis=1).copy()
    y = housing['median_house_value']
    return X, y





if __name__ == '__main__':

    # to randomly split data into train and test part
    X, y = load_data()
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

    num_features = [ 'longitude', 'latitude', 'housing_median_age', 'total_rooms',
           'total_bedrooms', 'population', 'households', 'median_income']

    cat_features = [ 'ocean_proximity' ]

    #drop_features = ['longitude', 'latitude']

    #pass_through =  [ 'median_income']

    num_pipeline = Pipeline([
        ('imputer', SimpleImputer(strategy='median')), #T1
        ('add features', Add_Features()),
        ('standard scaler', StandardScaler()), #T2
    ])


    final_pipeline = ColumnTransformer([
        # (name, Transformer, column_list)
        ("numerical pipeline", num_pipeline, num_features),
        ("categorical pipeline", OneHotEncoder(), cat_features),
        # ('remove features', 'drop', drop_features),
        # ('pass throgh', 'passthrough', pass_through )
    ])

    X_train_tr = final_pipeline.fit_transform(X_train)
    # cat_col = list(final_pipeline.named_transformers_['categorical pipeline'].categories_[0])
    # columns = num_features + list(cat_col) #+ pass_through

    #X_train_tr = pd.DataFrame(X_train_tr, columns=columns)
    X_test_tr  =  final_pipeline.transform(X_test)
    #X_test_tr = pd.DataFrame(X_test_tr, columns=columns)
    
    models = [
        ('Linear Regression', LinearRegression()),
        ('SGD Regressor', SGDRegressor(max_iter=10000)),
        ('Decision Tree', DecisionTreeRegressor(max_depth=7)),
        ('Support Vector Machines', SVR(kernel='linear')),
        ('Random Forest', RandomForestRegressor(max_depth=9)),
        ('K-Nearest Neighbors', KNeighborsRegressor(n_neighbors=51))
    ]

    model_report(models, X_train_tr, X_test_tr, y_train, y_test)

Overwriting housing_project.py


#### Tuesday 

    Model Evaluation -> Cross Validation ( X_train, X_val, X_test)
    
    Hyper Parameter Tuning -> GridSearcCV, RandomizedSearch
    
    Model Deploy
    
    